name: TFLint and SYNK scan
on: 
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  TFLint and SYNK checks:
    runs-on: ubuntu-latest
    steps:
      - uses: terraform-linters/setup-tflint@v3
        with:
         tflint_version: latest
   
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
    
      - name: Run TFLint
        run: tflint -f compact

      - uses: actions/checkout@v2
      - name: Run Snyk to check Terraform files for issues
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=critical